spring.application.name=iJuris


# Habilita o console web do H2 (acesse em http://localhost:8080/h2-console)
spring.h2.console.enabled=true

# Define a estratégia de criação das tabelas pelo Hibernate
spring.jpa.hibernate.ddl-auto=create-drop

# Garante que o script de dados rode APÓS o Hibernate criar as tabelas
spring.jpa.defer-datasource-initialization=true
